# Identificación de la aplicación
spring.application.name=hotel-booking-service

# CONFIGURACIÓN DE BASE DE DATOS (La Wallet de Oracle Cloud)
# Utiliza WALLET_PATH como variable de entorno (Docker), y como fallback usa la ruta local.
spring.datasource.url=jdbc:oracle:thin:@midbduoc_high?TNS_ADMIN=${WALLET_PATH:C:/Users/Volg/Documents/HotelBooking/hotel-booking-service/Wallet_MIDBDUOC}
spring.datasource.username=hotelbooking
spring.datasource.password=SumativasFullStack2026
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# CONFIGURACIÓN DE JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CONFIGURACIÓN DE LOGGING
# Establecer el nivel de log global
logging.level.root=INFO
# Nivel DEBUG
logging.level.com.example.hotel_booking=DEBUG
# Nivel INFO
logging.level.org.springframework=INFO
# Ver las consultas SQL generadas
logging.level.org.hibernate.SQL=DEBUG

# SEGURIDAD (Basic Auth)
spring.security.user.name=hotelbooking
spring.security.user.password=SumativasFullStack2026

